# Generated by Django 4.2 on 2023-04-23 03:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("anime_series", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AnimeSeries",
            new_name="AnimeSerie",
        ),
    ]
