# Generated by Django 4.2 on 2023-04-23 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("anime_series", "0002_rename_animeseries_animeserie"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("image", models.URLField()),
                ("description", models.CharField(max_length=800)),
                ("order", models.PositiveIntegerField()),
                (
                    "character_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Character",
                        to="anime_series.animeserie",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
