# Generated by Django 4.2 on 2023-04-23 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("anime_series", "0003_character"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animeserie",
            name="description",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
