# Generated by Django 4.1.5 on 2023-04-23 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime_series', '0004_alter_animeserie_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='character_id',
            new_name='anime_id',
        ),
    ]
